### Dio - Santander Bootcamp de Data Science, Pipeline de ETL com Python - Desafio Final
O objetivo deste desafio é replicar o projeto prático, explorando os conceitos de Ciência de Dados e Python. Crie seu repositório no GitHub e mostre ao mercado que você sabe construir soluções práticas 😎

Neste Lab, o foco principal é aprender o fluxo ETL (Extração, Transformação e Carregamento). A ferramenta específica (API, arquivo ou IA) é menos importante do que entender como os dados fluem de uma etapa para a outra.

### Arquivo de referência
- [Desafio_Pipeline_ETL_Python.ipynb](Desafio_Pipeline_ETL_Python.ipynb)
- https://github.com/falvojr/santander-dev-week-2023/blob/master/SantanderDevWeek2023.ipynb

---------------------------

In [18]:
# Bibliotecas necessárias
import pandas as pd
import requests 
import json
from pathlib import Path
import pandas as pd

In [19]:
# Localização dos dados (ajuste se necessário)
arquivo_rede = "C:\\Users\\gbsuf\\OneDrive\\Documentos\\Gestao do Conhecimento\\DIO - BootcampSantander 2026\\5 - Fundamentos de ETL\\Desafio_ETL\\desafio_etl_dio_santander_sample.csv"
print(arquivo_rede)

C:\Users\gbsuf\OneDrive\Documentos\Gestao do Conhecimento\DIO - BootcampSantander 2026\5 - Fundamentos de ETL\Desafio_ETL\desafio_etl_dio_santander_sample.csv

In [20]:
# Lê o arquivo Desafio_Pipeline_ETL_Python.csv
df_rede = pd.read_csv(arquivo_rede)
df_rede.head()

,id,name,account_id,account_number,account_agency,account_balance,account_limit,card_id,card_number,card_limit,features,news
0,1,Pyterson,7,00001-1,1,0.0,500.0,4,**** **** **** 1111,1000.0,[],"[{'id': 9, 'icon': 'https://digitalinnovationo..."
1,2,Pip,8,00002-2,1,0.0,500.0,5,**** **** **** 2222,1000.0,[],"[{'id': 10, 'icon': 'https://digitalinnovation..."
2,3,Pep,9,00003-3,1,0.0,500.0,6,**** **** **** 3333,1000.0,[],"[{'id': 11, 'icon': 'https://digitalinnovation..."

In [21]:
# Novos usuários a serem adicionados
novos_usuarios = [
    {
        "id": 3,
        "name": "Lia",
        "account_id": 10,
        "account_number": "00004-4",
        "account_agency": "0001",
        "account_balance": 150.0,
        "account_limit": 600.0,
        "card_id": 3,
        "card_number": "**** **** **** 4444",
        "card_limit": 1200.0,
        "features": "[]",
        "news": str([
            {
                "id": 12,
                "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/pix.svg",
                "description": "Lia, aproveite o Pix para organizar seus pagamentos e manter suas finanças em dia."
            }
        ])
    },
    {
        "id": 4,
        "name": "Rafa",
        "account_id": 11,
        "account_number": "00005-5",
        "account_agency": "0001",
        "account_balance": 320.0,
        "account_limit": 800.0,
        "card_id": 4,
        "card_number": "**** **** **** 5555",
        "card_limit": 1500.0,
        "features": "[]",
        "news": str([
            {
                "id": 13,
                "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/invest.svg",
                "description": "Rafa, pequenas aplicações mensais podem transformar seu futuro financeiro."
            }
        ])
    }
]

In [22]:
# Adiciona os novos usuários ao DataFrame existente
for usuario in novos_usuarios:
    df_rede = pd.concat([df_rede, pd.DataFrame([usuario])], ignore_index=True) # ignore_index para reindexar as linhas corretamente
df_rede.tail()  # Verifica os novos usuários adicionados

,id,name,account_id,account_number,account_agency,account_balance,account_limit,card_id,card_number,card_limit,features,news
0,1,Pyterson,7,00001-1,1,0.0,500.0,4,**** **** **** 1111,1000.0,[],"[{'id': 9, 'icon': 'https://digitalinnovationo..."
1,2,Pip,8,00002-2,1,0.0,500.0,5,**** **** **** 2222,1000.0,[],"[{'id': 10, 'icon': 'https://digitalinnovation..."
2,3,Pep,9,00003-3,1,0.0,500.0,6,**** **** **** 3333,1000.0,[],"[{'id': 11, 'icon': 'https://digitalinnovation..."
3,3,Lia,10,00004-4,0001,150.0,600.0,3,**** **** **** 4444,1200.0,[],"[{'id': 12, 'icon': 'https://digitalinnovation..."
4,4,Rafa,11,00005-5,0001,320.0,800.0,4,**** **** **** 5555,1500.0,[],"[{'id': 13, 'icon': 'https://digitalinnovation..."

In [23]:
# Exibir o número total de usuários após a adição
print(f"Número total de usuários após a adição: {len(df_rede)}")

Número total de usuários após a adição: 5

In [24]:
# Exibir os nomes dos usuários na lista
print("Nomes dos usuários na lista:")
for nome in df_rede['name']:
    print(nome)

Nomes dos usuários na lista:
Pyterson
Pip
Pep
Lia
Rafa

### Gerar uma mensagem para cada usuário utilizando IA
- Documentação Oficial da API OpenAI: https://platform.openai.com/docs/api-reference/introduction
- Informações sobre o Período Gratuito: https://help.openai.com/en/articles/4936830

##### Para gerar uma API Key:
- 1. Crie uma conta na OpenAI
- 2. Acesse a seção "API Keys"
- 3. Clique em "Create API Key"
- Link direto: https://platform.openai.com/account/api-keys

In [ ]:
# Código para gerar uma nova mensagem personalizada para cada usuário utilizando a API do OpenAI
!pip install openai
import openai

ModuleNotFoundError: No module named 'openai'

In [ ]:
# Configuração da API do OpenAI 
openai.api_key = 'SUA_CHAVE_DE_API_AQUI'  # Substitua pela sua chave de API do OpenAI

openai.api_key = openai_api_key

def generate_ai_news(user):
  completion = openai.ChatCompletion.create(
    model="gpt-4",
    messages=[
      {
          "role": "system",
          "content": "Você é um especialista em markting bancário."
      },
      {
          "role": "user",
          "content": f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)"
      }
    ]
  )
  return completion.choices[0].message.content.strip('\"')

for user in users:
  news = generate_ai_news(user)
  print(news)
  user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": news
  })

### Nota: não gerei as mensagens utilizando IA, apenas deixei o código de exemplo para referência futura. Quis evitar custos adicionais.

In [ ]:
# Atualizar a lista de news para cada usuário com a mensagem gerada pela IA
for i, user in df_rede.iterrows():
    news = generate_ai_news(user)
    news_entry = {
        "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
        "description": news
    }
    # Atualiza a coluna 'news' convertendo a string de volta para lista e adicionando a nova entrada
    current_news = json.loads(user['news'].replace("'", "\""))
    current_news.append(news_entry)
    df_rede.at[i, 'news'] = str(current_news)

In [ ]:
# Exibir as notícias atualizadas para cada usuário
for i, user in df_rede.iterrows():
    print(f"Notícias para {user['name']}: {user['news']}")
# Salvar o DataFrame atualizado em um novo arquivo CSV
arquivo_atualizado = "C:\\Users\\gbsuf\\OneDrive\\Documentos\\Gestao do Conhecimento\\DIO - BootcampSantander 2026\\5 - Fundamentos de ETL\\Desafio_ETL\\desafio_etl_dio_santander_atualizado.csv"
df_rede.to_csv(arquivo_atualizado, index=False)